// ─────────────────────────────────────────────────────────────────────────────
// Broker tick feed — SCAFFOLD, NOT VERIFIED
//
// Read this before you trust anything in here.
//
// Everything else in this server is verified against real responses. This file
// is not, and cannot be, because a broker tick socket needs a paid subscription
// and a session token that only you can generate by logging in. The transport
// (WebSocket, subscribe frames, reconnect/backoff, tick fan-out) is written and
// exercised; the per-broker binary tick layouts are transcribed from published
// docs and have never received a real byte from a real socket on this machine.
//
// So: `tested: false` is reported honestly on /api/broker/status, and nothing in
// the app silently switches over to this feed. Yahoo (delayed) and the NSE
// indices endpoint (live, indices only) remain the defaults until you connect a
// broker and confirm the ticks look right.
//
// Why bother at all: without a broker socket there is no true intraday live
// price for individual stocks from this machine. Yahoo returns the previous
// close during and after market hours, and NSE's per-stock quote endpoints sit
// behind a bot wall that server-side curl cannot pass. That gap is structural,
// not a bug to be worked around.
// ─────────────────────────────────────────────────────────────────────────────

// ── Adapters ────────────────────────────────────────────────────────────────
// Each adapter documents exactly what it needs and how its frames are shaped,
// so wiring in real credentials is a config change, not a code hunt.
export const ADAPTERS = {
  zerodha: {
    label: "Zerodha Kite Connect",
    docs: "https://kite.trade/docs/connect/v3/websocket/",
    env: ["KITE_API_KEY", "KITE_ACCESS_TOKEN"],
    subscription: "Kite Connect ₹500/month + daily login to mint an access token",
    tokenLife: "Access token expires every trading day around 07:30 IST — it must be regenerated by logging in",
    url: (e) => `wss://ws.kite.trade/?api_key=${e.KITE_API_KEY}&access_token=${e.KITE_ACCESS_TOKEN}`,
    // Instrument tokens are numeric and come from Kite's instruments dump, not
    // from the Yahoo symbols this app uses elsewhere. Mapping is your job.
    subscribe: (tokens) => [
      JSON.stringify({ a: "subscribe", v: tokens }),
      JSON.stringify({ a: "mode", v: ["full", tokens] }),
    ],
    binary: true,
    // Kite sends big-endian binary: int16 packet count, then per packet
    // int16 length + payload. A 'full' quote packet is 184 bytes; LTP sits at
    // offset 4 as an int32 in paise, so divide by 100 for equity/index.
    parse: (buf) => {
      const dv = new DataView(buf.buffer ?? buf, buf.byteOffset ?? 0, buf.byteLength);
      if (dv.byteLength < 4) return [];
      const count = dv.getInt16(0);
      const out = [];
      let p = 2;
      for (let i = 0; i < count && p + 2 <= dv.byteLength; i++) {
        const len = dv.getInt16(p); p += 2;
        if (len < 8 || p + len > dv.byteLength) break;
        out.push({
          token: dv.getInt32(p),
          ltp: dv.getInt32(p + 4) / 100,
          ts: len >= 44 ? dv.getInt32(p + 40) * 1000 : Date.now(),
          raw: len,
        });
        p += len;
      }
      return out;
    },
  },

  upstox: {
    label: "Upstox API v2",
    docs: "https://upstox.com/developer/api-documentation/websocket",
    env: ["UPSTOX_ACCESS_TOKEN"],
    subscription: "Free with an Upstox account, but the feed URL must be fetched via REST first",
    tokenLife: "Access token expires daily at 03:30 IST",
    // Upstox does not accept a static socket URL: you GET an authorised,
    // short-lived redirect URL first. That call is the reason connect() below
    // has an async prepare() hook.
    prepare: async (e) => {
      const r = await fetch("https://api.upstox.com/v2/feed/market-data-feed/authorize", {
        headers: { Authorization: `Bearer ${e.UPSTOX_ACCESS_TOKEN}`, Accept: "application/json" },
      });
      if (!r.ok) throw new Error(`Upstox authorize failed: ${r.status} ${await r.text()}`);
      const j = await r.json();
      const url = j?.data?.authorizedRedirectUri;
      if (!url) throw new Error("Upstox authorize returned no authorizedRedirectUri");
      return url;
    },
    subscribe: (keys) => [JSON.stringify({ guid: "tt", method: "sub", data: { mode: "ltpc", instrumentKeys: keys } })],
    binary: true,
    // Upstox v2 frames are protobuf. Decoding them needs the generated schema
    // from their repo; deliberately not stubbed here, because a fake parser
    // that returns plausible numbers is worse than no parser at all.
    parse: () => { throw new Error("Upstox protobuf decoder not implemented — add their generated schema"); },
  },

  dhan: {
    label: "Dhan HQ v2",
    docs: "https://dhanhq.co/docs/v2/live-market-feed/",
    env: ["DHAN_CLIENT_ID", "DHAN_ACCESS_TOKEN"],
    subscription: "Free data feed with a Dhan account",
    tokenLife: "Access token is long-lived (set by you in the Dhan dashboard)",
    url: (e) => `wss://api-feed.dhan.co?version=2&token=${e.DHAN_ACCESS_TOKEN}&clientId=${e.DHAN_CLIENT_ID}&authType=2`,
    subscribe: (ids) => [JSON.stringify({
      RequestCode: 15, InstrumentCount: ids.length,
      InstrumentList: ids.map(id => ({ ExchangeSegment: "NSE_EQ", SecurityId: String(id) })),
    })],
    binary: true,
    // Dhan ticker packet: 8-byte header (code, len, segment, int32 security id)
    // then a little-endian float32 LTP.
    parse: (buf) => {
      const dv = new DataView(buf.buffer ?? buf, buf.byteOffset ?? 0, buf.byteLength);
      if (dv.byteLength < 12) return [];
      return [{
        token: dv.getInt32(4, true),
        ltp: dv.getFloat32(8, true),
        ts: Date.now(),
        raw: dv.byteLength,
      }];
    },
  },
};

// ── Runtime state ───────────────────────────────────────────────────────────
const state = {
  provider: null, socket: null, status: "disconnected",
  error: null, connectedAt: null, tickCount: 0,
  ticks: new Map(),          // token -> last tick
  tokens: [], attempts: 0, timer: null, closedByUs: false,
};

const missingEnv = (a) => a.env.filter(k => !process.env[k]);

export function brokerStatus() {
  const providers = Object.entries(ADAPTERS).map(([key, a]) => ({
    key, label: a.label, docs: a.docs, subscription: a.subscription,
    tokenLife: a.tokenLife, env: a.env, missingEnv: missingEnv(a),
    configured: missingEnv(a).length === 0,
    parserImplemented: (() => { try { a.parse(new Uint8Array(0)); return true; } catch (e) { return !/not implemented/.test(e.message); } })(),
  }));
  return {
    tested: false,
    warning: "Never received a real tick on this machine. Transport is written; per-broker binary layouts are transcribed from docs and unverified. Do not trade off this feed until you have eyeballed the ticks against your broker's own screen.",
    fallback: "Until then the app uses NSE for live index prices and Yahoo (delayed) for everything else.",
    providers,
    anyConfigured: providers.some(p => p.configured),
    connection: {
      provider: state.provider, status: state.status, error: state.error,
      connectedAt: state.connectedAt, tickCount: state.tickCount,
      subscribed: state.tokens.length, reconnectAttempts: state.attempts,
    },
  };
}

export function lastTicks() {
  return { tested: false, provider: state.provider, status: state.status, count: state.tickCount, ticks: [...state.ticks.values()] };
}

export async function brokerConnect({ provider, tokens = [] }) {
  const a = ADAPTERS[provider];
  if (!a) throw new Error(`Unknown provider "${provider}" — one of: ${Object.keys(ADAPTERS).join(", ")}`);
  const miss = missingEnv(a);
  if (miss.length) throw new Error(`${a.label} needs ${miss.join(" and ")} in server/.env. ${a.subscription}. ${a.tokenLife}`);
  if (!tokens.length) throw new Error(`No instrument tokens given. These are ${a.label}'s own numeric IDs, not the Yahoo symbols used elsewhere in this app.`);

  brokerDisconnect();
  state.provider = provider; state.tokens = tokens; state.closedByUs = false;
  await open(a);
  return brokerStatus();
}

async function open(a) {
  state.status = "connecting"; state.error = null;
  let url;
  try { url = a.prepare ? await a.prepare(process.env) : a.url(process.env); }
  catch (e) { state.status = "error"; state.error = e.message; return; }

  const ws = new WebSocket(url);
  if (a.binary) ws.binaryType = "arraybuffer";
  state.socket = ws;

  ws.onopen = () => {
    state.status = "connected"; state.connectedAt = new Date().toISOString(); state.attempts = 0;
    for (const frame of a.subscribe(state.tokens)) ws.send(frame);
  };
  ws.onmessage = (ev) => {
    try {
      const data = ev.data instanceof ArrayBuffer ? new Uint8Array(ev.data) : ev.data;
      if (typeof data === "string") return;                  // heartbeat / order updates
      for (const t of a.parse(data)) { state.ticks.set(t.token, t); state.tickCount++; }
    } catch (e) { state.error = `tick parse failed: ${e.message}`; }
  };
  ws.onerror = () => { state.error = state.error || "socket error"; };
  ws.onclose = () => {
    state.status = state.closedByUs ? "disconnected" : "reconnecting";
    state.socket = null;
    if (state.closedByUs) return;
    // Exponential backoff capped at 30s. Broker sockets drop at session close
    // and on daily token expiry; the second case will never recover, which is
    // why the error is surfaced instead of being retried forever in silence.
    state.attempts++;
    if (state.attempts > 8) { state.status = "error"; state.error = "gave up after 8 reconnect attempts — token has probably expired"; return; }
    const wait = Math.min(30000, 1000 * 2 ** state.attempts);
    state.timer = setTimeout(() => open(a), wait);
  };
}

export function brokerDisconnect() {
  state.closedByUs = true;
  if (state.timer) { clearTimeout(state.timer); state.timer = null; }
  try { state.socket?.close(); } catch {}
  state.socket = null; state.status = "disconnected"; state.attempts = 0;
  return { status: state.status };
}
